services:

  nginx:
    restart: unless-stopped
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/nginx-certs:/certs/
      - ~/nginx_local/servers/:/etc/nginx/conf.d/servers
      - ~/nginx_local/includes/:/etc/nginx/conf.d/includes
      - ~/nginx_local/static/:/usr/share/nginx/html
    ports:
      - 443:443
      - 80:80
    networks:
        - local-nginx-net
  
  portainer:
    restart: always
    image: portainer/portainer-ce:lts
    container_name: portainer
    expose:
        - 8000
        - 9443
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    networks:
        - local-nginx-net


 

    
networks:
  local-nginx-net:
    name: local-nginx-net
volumes:
  portainer_data:
    external: true
